# Generated by Django 3.2.3 on 2023-03-26 14:43

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230325_1222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='no_me',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Это имя занято.'}, help_text='Обязательно к заполнению. <=150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
